repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-added-large-files
        args: ['--maxkb=5000']
    -   id: end-of-file-fixer

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: [
            # only error for syntax errors and undefined names
            "--select=E9,F63,F7,F82",
        ]
